### ISSUE TITLE
how to change the "example" wording

### ISSUE THREAD

**Issue by raynamharris** [ctb/ribbity#32]
How do I change the text from "Example" to something else.

Like, if all my examples are workshops, how do I change it so that the text appears as "All workshops" and "Workshop: "

![Screen Shot 2022-05-25 at 9 48 48 AM](https://user-images.githubusercontent.com/7544197/170317856-202b2358-fdb5-4b73-b1e7-c843661b682a.png)

**Comment by ctb** [comment]
Conveniently, I added this in the `main` branch but it's not yet released! I can cut a release if you want to give it a try.

**Comment by raynamharris** [comment]
no worries. i can wait.

**Comment by ctb** [comment]
It's in #29, and the config option will be:

`issue_title_prefix`

which defaults to `Example: `

**Comment by raynamharris** [comment]
cool!

**Comment by ctb** [comment]
released in https://github.com/ribbity-org/ribbity/releases/tag/v0.4, give it a try!

**Comment by ctb** [comment]
example site config etc here - https://ribbity-org.github.io/ribbity-sandbox/examples.html
